### ISSUE TITLE
Picking the release - example wold be excellent

### ISSUE THREAD

**Issue by gergelytakacs** [matlab-actions/overview#10]
Hello,

I'm using the MATLAB for an open-source project [2] on GitHub. The setup MATLAB action [1] mentions the possibility to pick a release, however it is unclear how this can be implemented. Can you please give an example?

Thank you!

Gergely (AutomationShield)

[1] https://github.com/matlab-actions/overview#setup-matlab
[2] https://github.com/gergelytakacs/AutomationShield

**Comment by kyak** [comment]
https://github.com/matlab-actions/setup-matlab/#set-up-matlab

**Comment by gergelytakacs** [comment]
@kyak  Thanks, that is clear. Where do you put the input, how? What syntax?

**Comment by gergelytakacs** [comment]
Found https://github.com/matlab-actions/setup-matlab/issues/28 this is what I needed.
