### ISSUE TITLE
Support for Windows Runners?

### ISSUE THREAD

**Issue by Kerstin-Keller** [matlab-actions/overview#5]
This action ist really great!
However I wonder if you have a roadmap to also support Windows Runners anytime in the near future?

**Comment by mcafaro** [comment]
Hi @Kerstin-Keller ,

Thanks for the feedback! Yes, Windows support is in the works. We have an [open issue](https://github.com/matlab-actions/setup-matlab/issues/18) on the setup-matlab repo for Windows support, so I'm going to close this one to consilidate.

Best,
Mark
