### ISSUE TITLE
MATLAB crashes when mexifying the official `timestwo.F`

### ISSUE THREAD

**Issue by zaikunzhang** [matlab-actions/overview#7]
This is a bug of MATLAB. It is encountered during a [GitHub Action](https://github.com/zaikunzhang/test_matlab/actions). See my [GitHub repo named test_matlab](https://github.com/zaikunzhang/test_matlab) for details. 

**In brief, MATLAB crashes when mexifying the official `timestwo.F`.**

To produce the crash, you may go to my [repo](https://github.com/zaikunzhang/test_matlab), download [crash.m](https://github.com/zaikunzhang/test_matlab/blob/master/crash.m), and run it on MATLAB. The crash has occurred on the following versions of MATLAB, all under Linux. macOS and Windows are yet to test. 

R2018b Update 3 (9.5.0.1049112) 64-bit (glnxa64
R2019b Update 5 (9.7.0.1319299) 64-bit (glnxa64)
R2020a (9.8.0.1323502) 64-bit (glnxa64)
R2021a Update 5 (9.10.0.1739362) 64-bit (glnxa64)
R2021b Update 1 (9.11.0.1809720) (glnxa64)

I look forward to seeing this bug fixed. Thanks. 

-------------------------------------------

Update (2022-02-18): I have included in my repo [some workarounds that can circumvent](https://github.com/zaikunzhang/test_matlab/tree/master/fix) the crash. However, the bug still needs to be fixed by MathWorks.

**Comment by kyak** [comment]
I find it absolutely gorgeous that now you can reproduce MATLAB crashes with Github Actions.

Should be easier for developers to triage and fix it. Let's see :)

**Comment by mcafaro** [comment]
Hi @zaikunzhang, thank you for reporting this issue and for the thorough reproduction steps. I was able to reproduce this issue locally on Linux but not on macOS or Windows.

Because I can reproduce this issue outside of GitHub Actions it does not appear to be an issue with our actions but instead with the underlying MEX command. I am going to forward this to the MEX team to have a look.

**Comment by zaikunzhang** [comment]
Thank you very much @mcafaro ! I look forward to a fix of this problem by the MEX team.
